---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dwdraju/alpine-curl-jq
    tag: latest
inputs:
  - name: cnx-automation
  - name: history-txt
run:
  path: bash
  args: ["cnx-automation/.concourse/tasks/run-functional-tests/script.bash"]

