version: "3"

services:
  selenium-chrome:
    environment:
      - DISPLAY=:0
      - RUNSLOW
      - LEGACY_BASE_URL
      - LEGACY_USERNAME
      - LEGACY_PASSWORD
    build: ./
    volumes:
      - .:/code
    expose:
      - "4444"
    ports:
      - "5900"
    shm_size: 2g
