version: "3"

services:
  selenium-chrome:
    environment:
      - DISPLAY=:0
      - GITHUB_TOKEN
      - HEADLESS
      - PRINT_PAGE_SOURCE_ON_FAILURE
      - RUNSLOW
      - ARCHIVE_BASE_URL
      - LEGACY_BASE_URL
      - LEGACY_USERNAME
      - LEGACY_PASSWORD
      - NEB_ENV
      - WEBVIEW_BASE_URL
    build: .
    volumes:
      - .:/code
    expose:
      - "4444"
    ports:
      - "5900"
    shm_size: 2g
