version: 2
jobs:
  build:
    docker:
      - image: openstax/selenium-chrome-debug:3.141.59
        environment:
          WEBVIEW_BASE_URL: https://staging.cnx.org
          LEGACY_BASE_URL: https://legacy-staging.cnx.org
          ARCHIVE_BASE_URL: https://archive-staging.cnx.org
          REX_BASE_URL: https://staging.openstax.org
    steps:
      - checkout
      - restore_cache:
            key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: make venv
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
      - run:
          name: start selenium server
          command: /opt/bin/entry_point.sh
          background: true
      - run:
          command: |
            . .venv/bin/activate
            pytest -m "webview and not visual" --headless -n 4
