version: 2
jobs:
  test-neb:
    docker:
      - image: circleci/python:3.7
        environment:
          NEB_ENV: staging
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: make venv
      - run:
          name: run tests for neb
          command: |
            . .venv/bin/activate
            pytest -m "neb" --junitxml=/tmp/test-reports/junit.xml
      - store_artifacts:
          path: /tmp/test-reports/junit.xml
          destination: test-reports
      - store_artifacts:
          path: report.html
          destination: test-reports
      - store_test_results:
          path: /tmp/test-reports
          test-neb:
  test-legacy:
    docker:
      - image: openstax/selenium-chrome-debug:3.141.59
        environment:
          WEBVIEW_BASE_URL: https://staging.cnx.org
          LEGACY_BASE_URL: https://legacy-staging.cnx.org
          ARCHIVE_BASE_URL: https://archive-staging.cnx.org
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: make venv
      - run:
          name: run tests for legacy
          command: |
            . .venv/bin/activate
            pytest -m legacy -k TestCreateImportPublishModuleAndCollection --runslow --headless --junitxml=/tmp/test-reports/junit.xml
      - store_artifacts:
          path: /tmp/test-reports/junit.xml
          destination: test-reports
      - store_artifacts:
          path: report.html
          destination: test-reports
      - store_test_results:
          path: /tmp/test-reports
          test-legacy:

workflows:
  version: 2
  test-neb:
    jobs:
      - test-neb

