version: 2
jobs:
  test:
    docker:
      - image: openstax/selenium-chrome-debug:3.141.59
        environment:
          WEBVIEW_BASE_URL: https://staging.cnx.org
          LEGACY_BASE_URL: https://legacy-staging.cnx.org
          ARCHIVE_BASE_URL: https://archive-staging.cnx.org
          REX_BASE_URL: https://staging.openstax.org
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
            key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: make venv
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
      - run:
          name: start selenium server via entrypoint
          command: /opt/bin/entry_point.sh
          background: true
      - run:
          name: install pytest-circleci-parallelized
          command: |
            . .venv/bin/activate
            pip install pytest-circleci-parallelized
      - run:
          name: run tests for webview
          command: |
            . .venv/bin/activate
            pytest -m "webview and not visual" --headless --circleci-parallelize
      - store_artifacts:
          path: report.html
workflows:
  version: 2
  test:
    jobs:
      - test
