version: 2
jobs:
  build:
    docker:
      - image: openstax/selenium-chrome-debug:3.141.59
        environment:
          WEBVIEW_BASE_URL: https://staging.cnx.org
          LEGACY_BASE_URL: https://legacy-staging.cnx.org
          ARCHIVE_BASE_URL: https://archive-staging.cnx.org
          REX_BASE_URL: https://staging.openstax.org
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
            key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: make venv
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
      - run:
          name: start selenium server via entrypoint
          command: /opt/bin/entry_point.sh
          background: true
      - run:
          name: run tests for webview
          command: |
            . .venv/bin/activate
            echo $(circleci tests glob "./tests/webview/**/*.py")
            circleci tests glob ./tests/webview/**/*.py |
            circleci tests split |
            xargs python -m pytest -m "webview and not visual" --headless
