resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: notify
    type: slack-notification
    source:
      url: ((slack-webhook-qa-stream))

  - name: source-code
    type: git
    source:
      uri: https://github.com/openstax/cnx-automation.git
      branch: master

  - name: cnx-auto-image
    type: docker-image
    source:
      repository: openstax/cnx-automation
      username: ((docker-hub-username))
      password: ((docker-hub-password))

jobs:
  - name: build-and-publish-image
    public: true
    plan:
      - get: source-code
        trigger: true
      - put: cnx-auto-image
        params:
          build: source-code
          tag_file: source-code/.git/short_ref
          tag_as_latest: true
    on_success:
      put: notify
      params:
        text: ":white_check_mark: cnx-automation docker image successfully uploaded to dockerhub."
    on_failure:
      put: notify
      params:
        text: ":warning: There was a problem building/uploading cnx-automation docker image to dockerhub."

