---
resource_types:

  - name: history-txt
    type: docker-image
    source:
      repository: openstax/concourse-history-txt-resource
      tag: latest

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:

  - name: history-qa
    type: history-txt
    source:
      instance: qa

  - name: history-staging
    type: history-txt
    source:
      instance: staging

  - name: history-prod
    type: history-txt
    source:
      instance: prod

  - name: cnx-automation
    type: git
    source:
      uri: https://github.com/openstax/cnx-automation
      branch: message-output-versions

  - name: notify
    type: slack-notification
    source:
      url: ((slack-webhook-cestream))

jobs:
  - name: test-qa
    plan:
      - get: history-qa
        trigger: true
      - get: cnx-automation
      - task: create-version-message
        file: cnx-automation/.concourse/tasks/version-message/task.yml
        input_mapping:
          history-txt: history-qa
          cnx-automation: cnx-automation
      - put: notify
        params:
          text_file: message-output/out.txt
      - task: run-functional-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: openstax/cnx-automation
          run:
            path: bash
            args:
              - -exc
              - |
                cd /code
                pytest -m "webview and smoke" --headless --disable-dev-shm-usage
          params:
            WEBVIEW_BASE_URL: "https://qa.cnx.org"
            LEGACY_BASE_URL: "https://legacy-qa.cnx.org"
            ARCHIVE_BASE_URL: "https://archive-qa.cnx.org"
    on_success:
      put: notify
      params:
        text: ":white_check_mark: All Chrome browser tests have passed on https://qa.cnx.org."
    on_failure:
      put: notify
      params:
        text: ":warning: There was a problem running Chrome browser tests on https://qa.cnx.org. This message will have more info one day. :joy:"


  - name: test-staging
    plan:
      - get: history-staging
        trigger: true
      - get: cnx-automation
      - task:
          -
      - task: create-version-message
        file: cnx-automation/.concourse/tasks/version-message/task.yml
        input_mapping:
          history-txt: history-staging
          cnx-automation: cnx-automation
      - put: notify
        params:
          text_file: message-output/out.txt
      - task: run-functional-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: openstax/cnx-automation
          run:
            path: bash
            args:
              - -exc
              - |
                cd /code
                pytest -m "webview and smoke" --headless --disable-dev-shm-usage
          params:
            WEBVIEW_BASE_URL: "https://staging.cnx.org"
            LEGACY_BASE_URL: "https://legacy-staging.cnx.org"
            ARCHIVE_BASE_URL: "https://archive-staging.cnx.org"
    on_success:
      put: notify
      params:
        text: ":white_check_mark: All Chrome browser tests have passed on https://staging.cnx.org."
    on_failure:
      put: notify
      params:
        text: ":warning: There was a problem running Chrome browser tests on https://staging.cnx.org. This message will have more info one day :joy:."

  - name: test-prod
    plan:
      - get: history-prod
        trigger: true
      - get: cnx-automation
      - task: create-version-message
        file: cnx-automation/.concourse/tasks/version-message/task.yml
        input_mapping:
          history-txt: history-prod
          cnx-automation: cnx-automation
      - put: notify
        params:
          text_file: message-output/out.txt
      - task: run-functional-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: openstax/cnx-automation
          run:
            path: bash
            args:
              - -exc
              - |
                cd /code
                pytest -m "webview and smoke" --headless --disable-dev-shm-usage
          params:
            WEBVIEW_BASE_URL: "https://cnx.org"
            LEGACY_BASE_URL: "https://legacy.cnx.org"
            ARCHIVE_BASE_URL: "https://archive.cnx.org"
    on_success:
      put: notify
      params:
        text: ":white_check_mark: All Chrome browser tests have passed on https://cnx.org."
    on_failure:
      put: notify
      params:
        text: ":warning: There was a problem running Chrome browser tests on https://cnx.org. This message will have more info one day :joy:."

