---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.7-slim
inputs:
  - name: cnx-automation
  - name: history-txt
  - name: run-circle-ci
outputs:
  - name: message-output
run:
  path: bash
  args:
    - -exc
    - |
      python cnx-automation/.concourse/tasks/version-message/script.py | tee message-output/out.txt
