---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dwdraju/alpine-curl-jq
    tag: latest
inputs:
  - name: cnx-automation
  - name: history-txt
outputs:
  - name: run-circleci
run:
  path: bash
  args: ["cnx-automation/.concourse/tasks/test-webview-ui-circleci/script.bash"]
params:
  CIRCLE_API_TOKEN: ((circleci-api-token))

